#include <Kophi/JavaInstruction.h>

#include <sstream>

namespace Kophi {
    static const JavaInstructionInfo instructionInfo[] = {
            { JavaInstruction::Nop,             "Nop",             1 },
            { JavaInstruction::AConst_Null,     "Aconst_Null",     1 },
            { JavaInstruction::IConst_m1,       "IConst_m1",       1 },
            { JavaInstruction::IConst_0,        "IConst_0",        1 },
            { JavaInstruction::IConst_1,        "IConst_1",        1 },
            { JavaInstruction::IConst_2,        "IConst_2",        1 },
            { JavaInstruction::IConst_3,        "IConst_3",        1 },
            { JavaInstruction::IConst_4,        "IConst_4",        1 },
            { JavaInstruction::IConst_5,        "IConst_5",        1 },
            { JavaInstruction::LConst_0,        "LConst_0",        1 },
            { JavaInstruction::LConst_1,        "LConst_1",        1 },
            { JavaInstruction::FConst_0,        "FConst_0",        1 },
            { JavaInstruction::FConst_1,        "FConst_1",        1 },
            { JavaInstruction::FConst_2,        "FConst_2",        1 },
            { JavaInstruction::DConst_0,        "DConst_0",        1 },
            { JavaInstruction::DConst_1,        "DConst_1",        1 },
            { JavaInstruction::BiPush,          "BiPush",          2 },
            { JavaInstruction::SiPush,          "SiPush",          3 },
            { JavaInstruction::Ldc,             "Ldc",             2 },
            { JavaInstruction::Ldc_w,           "Ldc_w",           3 },
            { JavaInstruction::Ldc2_w,          "Ldc2_w",          3 },
            { JavaInstruction::ILoad,           "ILoad",           2 },
            { JavaInstruction::LLoad,           "LLoad",           2 },
            { JavaInstruction::FLoad,           "FLoad",           2 },
            { JavaInstruction::DLoad,           "DLoad",           2 },
            { JavaInstruction::ALoad,           "ALoad",           2 },
            { JavaInstruction::ILoad_0,         "ILoad_0",         1 },
            { JavaInstruction::ILoad_1,         "ILoad_1",         1 },
            { JavaInstruction::ILoad_2,         "ILoad_2",         1 },
            { JavaInstruction::ILoad_3,         "ILoad_3",         1 },
            { JavaInstruction::LLoad_0,         "LLoad_0",         1 },
            { JavaInstruction::LLoad_1,         "LLoad_1",         1 },
            { JavaInstruction::LLoad_2,         "LLoad_2",         1 },
            { JavaInstruction::LLoad_3,         "LLoad_3",         1 },
            { JavaInstruction::FLoad_0,         "FLoad_0",         1 },
            { JavaInstruction::FLoad_1,         "FLoad_1",         1 },
            { JavaInstruction::FLoad_2,         "FLoad_2",         1 },
            { JavaInstruction::FLoad_3,         "FLoad_3",         1 },
            { JavaInstruction::DLoad_0,         "DLoad_0",         1 },
            { JavaInstruction::DLoad_1,         "DLoad_1",         1 },
            { JavaInstruction::DLoad_2,         "DLoad_2",         1 },
            { JavaInstruction::DLoad_3,         "DLoad_3",         1 },
            { JavaInstruction::ALoad_0,         "ALoad_0",         1 },
            { JavaInstruction::ALoad_1,         "ALoad_1",         1 },
            { JavaInstruction::ALoad_2,         "ALoad_2",         1 },
            { JavaInstruction::ALoad_3,         "ALoad_3",         1 },
            { JavaInstruction::IaLoad,          "IaLoad",          1 },
            { JavaInstruction::LaLoad,          "LaLoad",          1 },
            { JavaInstruction::FaLoad,          "FaLoad",          1 },
            { JavaInstruction::DaLoad,          "DaLoad",          1 },
            { JavaInstruction::AaLoad,          "AaLoad",          1 },
            { JavaInstruction::BaLoad,          "BaLoad",          1 },
            { JavaInstruction::CaLoad,          "CaLoad",          1 },
            { JavaInstruction::SaLoad,          "SaLoad",          1 },
            { JavaInstruction::IStore,          "IStore",          2 },
            { JavaInstruction::LStore,          "LStore",          2 },
            { JavaInstruction::FStore,          "FStore",          2 },
            { JavaInstruction::DStore,          "DStore",          2 },
            { JavaInstruction::AStore,          "AStore",          2 },
            { JavaInstruction::IStore_0,        "IStore_0",        1 },
            { JavaInstruction::IStore_1,        "IStore_1",        1 },
            { JavaInstruction::IStore_2,        "IStore_2",        1 },
            { JavaInstruction::IStore_3,        "IStore_3",        1 },
            { JavaInstruction::LStore_0,        "LStore_0",        1 },
            { JavaInstruction::LStore_1,        "LStore_1",        1 },
            { JavaInstruction::LStore_2,        "LStore_2",        1 },
            { JavaInstruction::LStore_3,        "LStore_3",        1 },
            { JavaInstruction::FStore_0,        "FStore_0",        1 },
            { JavaInstruction::FStore_1,        "FStore_1",        1 },
            { JavaInstruction::FStore_2,        "FStore_2",        1 },
            { JavaInstruction::FStore_3,        "FStore_3",        1 },
            { JavaInstruction::DStore_0,        "DStore_0",        1 },
            { JavaInstruction::DStore_1,        "DStore_1",        1 },
            { JavaInstruction::DStore_2,        "DStore_2",        1 },
            { JavaInstruction::DStore_3,        "DStore_3",        1 },
            { JavaInstruction::AStore_0,        "AStore_0",        1 },
            { JavaInstruction::AStore_1,        "AStore_1",        1 },
            { JavaInstruction::AStore_2,        "AStore_2",        1 },
            { JavaInstruction::AStore_3,        "AStore_3",        1 },
            { JavaInstruction::IaStore,         "IaStore",         1 },
            { JavaInstruction::LaStore,         "LaStore",         1 },
            { JavaInstruction::FaStore,         "FaStore",         1 },
            { JavaInstruction::DaStore,         "DaStore",         1 },
            { JavaInstruction::AaStore,         "AaStore",         1 },
            { JavaInstruction::BaStore,         "BaStore",         1 },
            { JavaInstruction::CaStore,         "CaStore",         1 },
            { JavaInstruction::SaStore,         "SaStore",         1 },
            { JavaInstruction::Pop,             "Pop",             1 },
            { JavaInstruction::Pop2,            "Pop2",            1 },
            { JavaInstruction::Dup,             "Dup",             1 },
            { JavaInstruction::Dup_x1,          "Dup_x1",          1 },
            { JavaInstruction::Dup_x2,          "Dup_x2",          1 },
            { JavaInstruction::Dup2,            "Dup2",            1 },
            { JavaInstruction::Dup2_x1,         "Dup2_x1",         1 },
            { JavaInstruction::Dup2_x2,         "Dup2_x2",         1 },
            { JavaInstruction::Swap,            "Swap",            1 },
            { JavaInstruction::Iadd,            "Iadd",            1 },
            { JavaInstruction::Ladd,            "Ladd",            1 },
            { JavaInstruction::Fadd,            "Fadd",            1 },
            { JavaInstruction::Dadd,            "Dadd",            1 },
            { JavaInstruction::Isub,            "Isub",            1 },
            { JavaInstruction::Lsub,            "Lsub",            1 },
            { JavaInstruction::Fsub,            "Fsub",            1 },
            { JavaInstruction::Dsub,            "Dsub",            1 },
            { JavaInstruction::Imul,            "Imul",            1 },
            { JavaInstruction::Lmul,            "Lmul",            1 },
            { JavaInstruction::Fmul,            "Fmul",            1 },
            { JavaInstruction::Dmul,            "Dmul",            1 },
            { JavaInstruction::Idiv,            "Idiv",            1 },
            { JavaInstruction::Ldiv,            "Ldiv",            1 },
            { JavaInstruction::Fdiv,            "Fdiv",            1 },
            { JavaInstruction::Ddiv,            "Ddiv",            1 },
            { JavaInstruction::Irem,            "Irem",            1 },
            { JavaInstruction::Lrem,            "Lrem",            1 },
            { JavaInstruction::Frem,            "Frem",            1 },
            { JavaInstruction::Drem,            "Drem",            1 },
            { JavaInstruction::Ineg,            "Ineg",            1 },
            { JavaInstruction::Lneg,            "Lneg",            1 },
            { JavaInstruction::Fneg,            "Fneg",            1 },
            { JavaInstruction::Dneg,            "Dneg",            1 },
            { JavaInstruction::Ishl,            "Ishl",            1 },
            { JavaInstruction::Lshl,            "Lshl",            1 },
            { JavaInstruction::Ishr,            "Ishr",            1 },
            { JavaInstruction::Lshr,            "Lshr",            1 },
            { JavaInstruction::Iushr,           "Iushr",           1 },
            { JavaInstruction::Lushr,           "Lushr",           1 },
            { JavaInstruction::Iand,            "Iand",            1 },
            { JavaInstruction::Land,            "Land",            1 },
            { JavaInstruction::Ior,             "Ior",             1 },
            { JavaInstruction::Lor,             "Lor",             1 },
            { JavaInstruction::Ixor,            "Ixor",            1 },
            { JavaInstruction::Lxor,            "Lxor",            1 },
            { JavaInstruction::Iinc,            "Iinc",            3 },
            { JavaInstruction::I2l,             "I2l",             1 },
            { JavaInstruction::I2f,             "I2f",             1 },
            { JavaInstruction::I2d,             "I2d",             1 },
            { JavaInstruction::L2i,             "L2i",             1 },
            { JavaInstruction::L2f,             "L2f",             1 },
            { JavaInstruction::L2d,             "L2d",             1 },
            { JavaInstruction::F2i,             "F2i",             1 },
            { JavaInstruction::F2l,             "F2l",             1 },
            { JavaInstruction::F2d,             "F2d",             1 },
            { JavaInstruction::D2i,             "D2i",             1 },
            { JavaInstruction::D2l,             "D2l",             1 },
            { JavaInstruction::D2f,             "D2f",             1 },
            { JavaInstruction::I2b,             "I2b",             1 },
            { JavaInstruction::I2c,             "I2c",             1 },
            { JavaInstruction::I2s,             "I2s",             1 },
            { JavaInstruction::Lcmp,            "Lcmp",            1 },
            { JavaInstruction::Fcmpl,           "Fcmpl",           1 },
            { JavaInstruction::Fcmpg,           "Fcmpg",           1 },
            { JavaInstruction::Dcmpl,           "Dcmpl",           1 },
            { JavaInstruction::Dcmpg,           "Dcmpg",           1 },
            { JavaInstruction::Ifeq,            "Ifeq",            1 },
            { JavaInstruction::Ifne,            "Ifne",            1 },
            { JavaInstruction::Iflt,            "Iflt",            1 },
            { JavaInstruction::Ifge,            "Ifge",            1 },
            { JavaInstruction::Ifgt,            "Ifgt",            1 },
            { JavaInstruction::Ifle,            "Ifle",            1 },
            { JavaInstruction::If_icmpeq,       "If_icmpeq",       3 },
            { JavaInstruction::If_icmpne,       "If_icmpne",       3 },
            { JavaInstruction::If_icmplt,       "If_icmplt",       3 },
            { JavaInstruction::If_icmpge,       "If_icmpge",       3 },
            { JavaInstruction::If_icmpgt,       "If_icmpgt",       3 },
            { JavaInstruction::If_icmple,       "If_icmple",       3 },
            { JavaInstruction::If_acmpeq,       "If_acmpeq",       3 },
            { JavaInstruction::If_acmpne,       "If_acmpne",       3 },
            { JavaInstruction::Goto,            "Goto",            3 },
            { JavaInstruction::Jsr,             "Jsr",             5 },
            { JavaInstruction::Ret,             "Ret",             2 },
            { JavaInstruction::TableSwitch,     "TableSwitch",     0 },
            { JavaInstruction::LookupSwitch,    "LookupSwitch",    0 },
            { JavaInstruction::IReturn,         "IReturn",         1 },
            { JavaInstruction::LReturn,         "LReturn",         1 },
            { JavaInstruction::FReturn,         "FReturn",         1 },
            { JavaInstruction::DReturn,         "DReturn",         1 },
            { JavaInstruction::AReturn,         "AReturn",         1 },
            { JavaInstruction::Return,          "Return",          1 },
            { JavaInstruction::GetStatic,       "GetStatic",       3 },
            { JavaInstruction::PutStatic,       "PutStatic",       3 },
            { JavaInstruction::GetField,        "GetField",        3 },
            { JavaInstruction::PutField,        "PutField",        3 },
            { JavaInstruction::InvokeVirtual,   "InvokeVirtual",   3 },
            { JavaInstruction::InvokeSpecial,   "InvokeSpecial",   3 },
            { JavaInstruction::InvokeStatic,    "InvokeStatic",    3 },
            { JavaInstruction::InvokeInterface, "InvokeInterface", 3 },
            { JavaInstruction::InvokeDynamic,   "InvokeDynamic",   3 },
            { JavaInstruction::New,             "New",             3 },
            { JavaInstruction::NewArray,        "NewArray",        2 },
            { JavaInstruction::ArrayLength,     "ArrayLength",     1 },
            { JavaInstruction::Athrow,          "Athrow",          1 },
            { JavaInstruction::CheckCast,       "CheckCast",       3 },
            { JavaInstruction::Instanceof,      "Instanceof",      3 },
            { JavaInstruction::Monitorenter,    "Monitorenter",    1 },
            { JavaInstruction::Monitorexit,     "Monitorexit",     1 },
            { JavaInstruction::Wide,            "Wide",            4 },
            { JavaInstruction::Multianewarray,  "Multianewarray",  4 },
            { JavaInstruction::Ifnull,          "Ifnull",          3 },
            { JavaInstruction::Ifnonnull,       "Ifnonnull",       3 },
            { JavaInstruction::Goto_w,          "Goto_w",          5 },
            { JavaInstruction::Jsr_w,           "Jsr_w",           5 },
    };

    const JavaInstructionInfo &lookupInstruction(JavaInstruction inst) {
        return instructionInfo[(uint8_t)inst];
    }

    std::string createDisasm(const unsigned char *data, unsigned length) {
        unsigned index = 0;
        std::stringstream stream;

        while (index < length) {
            JavaInstruction inst = (JavaInstruction) data[index];
            const JavaInstructionInfo &info = lookupInstruction(inst);
            stream << "\t\t\t" << info.name;
            for (int a = 1; a < info.length; a++) {
                stream << " " << (unsigned) data[index + a];
            }
            index += info.length;
            if (index < length)
                stream << "\n";
        }

        return stream.str();
    }
}
